WARNING:tensorflow:`period` argument is deprecated. Please use `save_freq` to specify the frequency in number of batches seen.
WARNING  `period` argument is deprecated. Please use `save_freq` to specify the frequency in number of batches seen.
Epoch 1/10
2023-04-04 12:39:07.168292: I tensorflow/core/grappler/devices.cc:66] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 4
2023-04-04 12:39:07.168569: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2023-04-04 12:39:07.228773: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 78600 MB memory:  -> device: 0, name: NVIDIA A100 80GB PCIe, pci bus id: 0000:17:00.0, compute capability: 8.0
2023-04-04 12:39:07.232040: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 78600 MB memory:  -> device: 1, name: NVIDIA A100 80GB PCIe, pci bus id: 0000:65:00.0, compute capability: 8.0
2023-04-04 12:39:07.235027: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:2 with 78600 MB memory:  -> device: 2, name: NVIDIA A100 80GB PCIe, pci bus id: 0000:ca:00.0, compute capability: 8.0
2023-04-04 12:39:07.236480: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:3 with 78600 MB memory:  -> device: 3, name: NVIDIA A100 80GB PCIe, pci bus id: 0000:e3:00.0, compute capability: 8.0
2023-04-04 12:39:07.269138: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:1137] Optimization results for grappler item: graph_to_optimize
  function_optimizer: function_optimizer did nothing. time = 0.057ms.
  function_optimizer: function_optimizer did nothing. time = 0.004ms.
WARNING:tensorflow:From /home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/site-packages/tensorflow/python/ops/math_ops.py:3777: tensor_shape_from_node_def_name (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.tensor_shape_from_node_def_name`
WARNING  From /home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/site-packages/tensorflow/python/ops/math_ops.py:3777: tensor_shape_from_node_def_name (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.tensor_shape_from_node_def_name`
2023-04-04 12:39:07.547057: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
2023-04-04 12:39:14.116529: I tensorflow/stream_executor/cuda/cuda_blas.cc:1760] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.
37/37 - 8s - loss: 0.5170 - accuracy: 0.8049 - auc: 0.5050 - precision: 0.1969 - recall: 0.0295 - balanced_accuracy: 0.5022 - val_loss: 0.4579 - val_accuracy: 0.8209 - val_auc: 0.6187 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_balanced_accuracy: 0.5000
Epoch 2/10
37/37 - 0s - loss: 0.4804 - accuracy: 0.8120 - auc: 0.5886 - precision: 0.3280 - recall: 0.0484 - balanced_accuracy: 0.5129 - val_loss: 0.4335 - val_accuracy: 0.8235 - val_auc: 0.6947 - val_precision: 1.0000 - val_recall: 0.0142 - val_balanced_accuracy: 0.5068
Epoch 3/10
37/37 - 0s - loss: 0.4675 - accuracy: 0.8110 - auc: 0.6214 - precision: 0.3462 - recall: 0.0638 - balanced_accuracy: 0.5193 - val_loss: 0.4182 - val_accuracy: 0.8387 - val_auc: 0.7160 - val_precision: 0.9200 - val_recall: 0.1085 - val_balanced_accuracy: 0.5571
Epoch 4/10
37/37 - 0s - loss: 0.4501 - accuracy: 0.8237 - auc: 0.6598 - precision: 0.5270 - recall: 0.1381 - balanced_accuracy: 0.5574 - val_loss: 0.4084 - val_accuracy: 0.8471 - val_auc: 0.7313 - val_precision: 0.8974 - val_recall: 0.1651 - val_balanced_accuracy: 0.5847
Epoch 5/10
37/37 - 0s - loss: 0.4348 - accuracy: 0.8253 - auc: 0.6882 - precision: 0.5431 - recall: 0.1488 - balanced_accuracy: 0.5613 - val_loss: 0.4006 - val_accuracy: 0.8505 - val_auc: 0.7434 - val_precision: 0.8723 - val_recall: 0.1934 - val_balanced_accuracy: 0.5970
Epoch 6/10
37/37 - 0s - loss: 0.4271 - accuracy: 0.8304 - auc: 0.7011 - precision: 0.5982 - recall: 0.1582 - balanced_accuracy: 0.5682 - val_loss: 0.3950 - val_accuracy: 0.8514 - val_auc: 0.7517 - val_precision: 0.8600 - val_recall: 0.2028 - val_balanced_accuracy: 0.6017
Epoch 7/10
37/37 - 0s - loss: 0.4140 - accuracy: 0.8393 - auc: 0.7215 - precision: 0.6569 - recall: 0.2125 - balanced_accuracy: 0.5969 - val_loss: 0.3911 - val_accuracy: 0.8488 - val_auc: 0.7574 - val_precision: 0.8113 - val_recall: 0.2028 - val_balanced_accuracy: 0.5984
Epoch 8/10
INFO     Computation time for training the single-label model for AR: 0.22 min
37/37 - 0s - loss: 0.4081 - accuracy: 0.8422 - auc: 0.7307 - precision: 0.6866 - recall: 0.2172 - balanced_accuracy: 0.5968 - val_loss: 0.3864 - val_accuracy: 0.8514 - val_auc: 0.7666 - val_precision: 0.8214 - val_recall: 0.2170 - val_balanced_accuracy: 0.6046
Epoch 9/10
37/37 - 0s - loss: 0.3985 - accuracy: 0.8420 - auc: 0.7522 - precision: 0.6701 - recall: 0.2302 - balanced_accuracy: 0.6012 - val_loss: 0.3830 - val_accuracy: 0.8522 - val_auc: 0.7723 - val_precision: 0.8246 - val_recall: 0.2217 - val_balanced_accuracy: 0.6080
Epoch 10/10
37/37 - 0s - loss: 0.3972 - accuracy: 0.8460 - auc: 0.7507 - precision: 0.7201 - recall: 0.2279 - balanced_accuracy: 0.6047 - val_loss: 0.3796 - val_accuracy: 0.8488 - val_auc: 0.7787 - val_precision: 0.7619 - val_recall: 0.2264 - val_balanced_accuracy: 0.6089
Epoch 00010: val_loss improved from inf to 0.37965, saving model to /home/zadubrov/output/results_train/AR_single-labeled_Fold-0.model.weights.hdf5
Traceback (most recent call last):
  File "/home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/__main__.py", line 415, in <module>
    main()
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/__main__.py", line 392, in main
    train(fixed_opts)
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/__main__.py", line 190, in train
    sl.train_single_label_models(df=df, opts=opts)
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/single_label_model.py", line 551, in train_single_label_models
    performance = fit_and_evaluate_model(x_train=x_train, x_test=x_test, y_train=y_train, y_test=y_test,
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/single_label_model.py", line 422, in fit_and_evaluate_model
    sd.shap_explain(x_train, model, target, opts.outputDir, drop_values=True, threshold=10, save_values=True)
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/shap_dfpl.py", line 26, in shap_explain
    explainer = shap.explainers.GPUTree(model.predict, data=x_train)
  File "/home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/site-packages/shap/explainers/_tree.py", line 149, in __init__
    self.model = TreeEnsemble(model, self.data, self.data_missing, model_output)
  File "/home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/site-packages/shap/explainers/_tree.py", line 993, in __init__
    raise InvalidModelError("Model type not yet supported by TreeExplainer: " + str(type(model)))
shap.utils._exceptions.InvalidModelError: Model type not yet supported by TreeExplainer: <class 'method'>
<IPython.core.display.HTML object>
[ True  True  True ...  True  True  True]
<bound method Model.predict of <keras.engine.sequential.Sequential object at 0x2b2526343820>>
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
<class 'numpy.ndarray'>	4735
<class 'tuple'>	2