WARNING:tensorflow:`period` argument is deprecated. Please use `save_freq` to specify the frequency in number of batches seen.
WARNING  `period` argument is deprecated. Please use `save_freq` to specify the frequency in number of batches seen.
Epoch 1/10
2023-04-03 15:28:51.332973: I tensorflow/core/grappler/devices.cc:66] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 4
2023-04-03 15:28:51.333185: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2023-04-03 15:28:51.349286: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 78600 MB memory:  -> device: 0, name: NVIDIA A100 80GB PCIe, pci bus id: 0000:17:00.0, compute capability: 8.0
2023-04-03 15:28:51.350182: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 78600 MB memory:  -> device: 1, name: NVIDIA A100 80GB PCIe, pci bus id: 0000:65:00.0, compute capability: 8.0
2023-04-03 15:28:51.351092: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:2 with 78600 MB memory:  -> device: 2, name: NVIDIA A100 80GB PCIe, pci bus id: 0000:ca:00.0, compute capability: 8.0
2023-04-03 15:28:51.351998: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:3 with 78600 MB memory:  -> device: 3, name: NVIDIA A100 80GB PCIe, pci bus id: 0000:e3:00.0, compute capability: 8.0
2023-04-03 15:28:51.365722: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:1137] Optimization results for grappler item: graph_to_optimize
  function_optimizer: function_optimizer did nothing. time = 0.027ms.
  function_optimizer: function_optimizer did nothing. time = 0.001ms.
WARNING:tensorflow:From /home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/site-packages/tensorflow/python/ops/math_ops.py:3777: tensor_shape_from_node_def_name (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.tensor_shape_from_node_def_name`
WARNING  From /home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/site-packages/tensorflow/python/ops/math_ops.py:3777: tensor_shape_from_node_def_name (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.tensor_shape_from_node_def_name`
2023-04-03 15:28:51.529549: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
2023-04-03 15:28:56.920312: I tensorflow/stream_executor/cuda/cuda_blas.cc:1760] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.
37/37 - 6s - loss: 0.4952 - accuracy: 0.8108 - auc: 0.5334 - precision: 0.2793 - recall: 0.0366 - balanced_accuracy: 0.5084 - val_loss: 0.4515 - val_accuracy: 0.8260 - val_auc: 0.6128 - val_precision: 1.0000 - val_recall: 0.0283 - val_balanced_accuracy: 0.5195
Epoch 2/10
37/37 - 0s - loss: 0.4701 - accuracy: 0.8211 - auc: 0.5929 - precision: 0.5000 - recall: 0.0638 - balanced_accuracy: 0.5252 - val_loss: 0.4339 - val_accuracy: 0.8370 - val_auc: 0.6682 - val_precision: 1.0000 - val_recall: 0.0896 - val_balanced_accuracy: 0.5466
Epoch 3/10
37/37 - 0s - loss: 0.4540 - accuracy: 0.8275 - auc: 0.6327 - precision: 0.6071 - recall: 0.1004 - balanced_accuracy: 0.5448 - val_loss: 0.4218 - val_accuracy: 0.8421 - val_auc: 0.6992 - val_precision: 0.9032 - val_recall: 0.1321 - val_balanced_accuracy: 0.5712
Epoch 4/10
37/37 - 0s - loss: 0.4352 - accuracy: 0.8344 - auc: 0.6776 - precision: 0.6933 - recall: 0.1334 - balanced_accuracy: 0.5589 - val_loss: 0.4125 - val_accuracy: 0.8421 - val_auc: 0.7244 - val_precision: 0.8378 - val_recall: 0.1462 - val_balanced_accuracy: 0.5761
Epoch 5/10
37/37 - 0s - loss: 0.4180 - accuracy: 0.8433 - auc: 0.7111 - precision: 0.8035 - recall: 0.1641 - balanced_accuracy: 0.5755 - val_loss: 0.4049 - val_accuracy: 0.8412 - val_auc: 0.7388 - val_precision: 0.7857 - val_recall: 0.1557 - val_balanced_accuracy: 0.5793
Epoch 6/10
37/37 - 0s - loss: 0.4143 - accuracy: 0.8420 - auc: 0.7162 - precision: 0.7415 - recall: 0.1795 - balanced_accuracy: 0.5821 - val_loss: 0.3987 - val_accuracy: 0.8429 - val_auc: 0.7506 - val_precision: 0.7955 - val_recall: 0.1651 - val_balanced_accuracy: 0.5845
Epoch 7/10
37/37 - 0s - loss: 0.4039 - accuracy: 0.8463 - auc: 0.7370 - precision: 0.7742 - recall: 0.1983 - balanced_accuracy: 0.5932 - val_loss: 0.3934 - val_accuracy: 0.8412 - val_auc: 0.7596 - val_precision: 0.7609 - val_recall: 0.1651 - val_balanced_accuracy: 0.5835
Epoch 8/10
37/37 - 0s - loss: 0.3977 - accuracy: 0.8427 - auc: 0.7503 - precision: 0.6992 - recall: 0.2113 - balanced_accuracy: 0.5977 - val_loss: 0.3892 - val_accuracy: 0.8429 - val_auc: 0.7673 - val_precision: 0.7600 - val_recall: 0.1792 - val_balanced_accuracy: 0.5888
Epoch 9/10
37/37 - 0s - loss: 0.3936 - accuracy: 0.8465 - auc: 0.7540 - precision: 0.7500 - recall: 0.2125 - balanced_accuracy: 0.5996 - val_loss: 0.3851 - val_accuracy: 0.8429 - val_auc: 0.7744 - val_precision: 0.7321 - val_recall: 0.1934 - val_balanced_accuracy: 0.5935
Epoch 10/10
37/37 - 0s - loss: 0.3879 - accuracy: 0.8479 - auc: 0.7667 - precision: 0.7414 - recall: 0.2302 - balanced_accuracy: 0.6084 - val_loss: 0.3814 - val_accuracy: 0.8454 - val_auc: 0.7797 - val_precision: 0.7302 - val_recall: 0.2170 - val_balanced_accuracy: 0.6043
Epoch 00010: val_loss improved from inf to 0.38139, saving model to /home/zadubrov/output/results_train/AR_single-labeled_Fold-0.model.weights.hdf5
INFO     Computation time for training the single-label model for AR: 0.16 min
<IPython.core.display.HTML object>
(array([0, 0, 0, ..., 0, 0, 0]), array([   0,    1,    2, ..., 2045, 2046, 2047]))
Traceback (most recent call last):
  File "/home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/__main__.py", line 415, in <module>
    main()
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/__main__.py", line 392, in main
    train(fixed_opts)
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/__main__.py", line 190, in train
    sl.train_single_label_models(df=df, opts=opts)
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/single_label_model.py", line 551, in train_single_label_models
    performance = fit_and_evaluate_model(x_train=x_train, x_test=x_test, y_train=y_train, y_test=y_test,
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/single_label_model.py", line 422, in fit_and_evaluate_model
    sd.shap_explain(x_train, model, target, opts.outputDir, drop_values=True, threshold=10, save_values=True)
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/shap_dfpl.py", line 20, in shap_explain
    print(x_train_to_explain = True)
TypeError: 'x_train_to_explain' is an invalid keyword argument for print()