WARNING:tensorflow:`period` argument is deprecated. Please use `save_freq` to specify the frequency in number of batches seen.
WARNING  `period` argument is deprecated. Please use `save_freq` to specify the frequency in number of batches seen.
Epoch 1/10
2023-04-26 12:34:49.023232: I tensorflow/core/grappler/devices.cc:66] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 4
2023-04-26 12:34:49.023889: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2023-04-26 12:34:49.144411: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 78600 MB memory:  -> device: 0, name: NVIDIA A100 80GB PCIe, pci bus id: 0000:17:00.0, compute capability: 8.0
2023-04-26 12:34:49.145984: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 78600 MB memory:  -> device: 1, name: NVIDIA A100 80GB PCIe, pci bus id: 0000:65:00.0, compute capability: 8.0
2023-04-26 12:34:49.147403: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:2 with 78600 MB memory:  -> device: 2, name: NVIDIA A100 80GB PCIe, pci bus id: 0000:ca:00.0, compute capability: 8.0
2023-04-26 12:34:49.153434: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:3 with 78600 MB memory:  -> device: 3, name: NVIDIA A100 80GB PCIe, pci bus id: 0000:e3:00.0, compute capability: 8.0
2023-04-26 12:34:49.185664: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:1137] Optimization results for grappler item: graph_to_optimize
  function_optimizer: function_optimizer did nothing. time = 0.062ms.
  function_optimizer: function_optimizer did nothing. time = 0.003ms.
WARNING:tensorflow:From /home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/site-packages/tensorflow/python/ops/math_ops.py:3777: tensor_shape_from_node_def_name (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.tensor_shape_from_node_def_name`
WARNING  From /home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/site-packages/tensorflow/python/ops/math_ops.py:3777: tensor_shape_from_node_def_name (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.tensor_shape_from_node_def_name`
2023-04-26 12:34:49.444646: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
2023-04-26 12:34:53.876832: I tensorflow/stream_executor/cuda/cuda_blas.cc:1760] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.
37/37 - 6s - loss: 0.5099 - accuracy: 0.8061 - auc: 0.5103 - precision: 0.1743 - recall: 0.0224 - balanced_accuracy: 0.4987 - val_loss: 0.4591 - val_accuracy: 0.8209 - val_auc: 0.6150 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_balanced_accuracy: 0.5000
Epoch 2/10
37/37 - 0s - loss: 0.4799 - accuracy: 0.8146 - auc: 0.5765 - precision: 0.3604 - recall: 0.0472 - balanced_accuracy: 0.5134 - val_loss: 0.4355 - val_accuracy: 0.8226 - val_auc: 0.6980 - val_precision: 1.0000 - val_recall: 0.0094 - val_balanced_accuracy: 0.5053
Epoch 3/10
37/37 - 1s - loss: 0.4637 - accuracy: 0.8213 - auc: 0.6173 - precision: 0.5037 - recall: 0.0803 - balanced_accuracy: 0.5306 - val_loss: 0.4190 - val_accuracy: 0.8302 - val_auc: 0.7408 - val_precision: 1.0000 - val_recall: 0.0519 - val_balanced_accuracy: 0.5240
Epoch 4/10
37/37 - 1s - loss: 0.4465 - accuracy: 0.8249 - auc: 0.6592 - precision: 0.5672 - recall: 0.0897 - balanced_accuracy: 0.5365 - val_loss: 0.4064 - val_accuracy: 0.8387 - val_auc: 0.7634 - val_precision: 1.0000 - val_recall: 0.0991 - val_balanced_accuracy: 0.5460
Epoch 5/10
37/37 - 0s - loss: 0.4358 - accuracy: 0.8329 - auc: 0.6789 - precision: 0.6707 - recall: 0.1299 - balanced_accuracy: 0.5576 - val_loss: 0.3972 - val_accuracy: 0.8412 - val_auc: 0.7746 - val_precision: 0.9615 - val_recall: 0.1179 - val_balanced_accuracy: 0.5537
Epoch 6/10
37/37 - 0s - loss: 0.4194 - accuracy: 0.8384 - auc: 0.7124 - precision: 0.6934 - recall: 0.1736 - balanced_accuracy: 0.5806 - val_loss: 0.3904 - val_accuracy: 0.8421 - val_auc: 0.7818 - val_precision: 0.8788 - val_recall: 0.1368 - val_balanced_accuracy: 0.5722
Epoch 7/10
37/37 - 0s - loss: 0.4095 - accuracy: 0.8410 - auc: 0.7272 - precision: 0.7009 - recall: 0.1936 - balanced_accuracy: 0.5861 - val_loss: 0.3850 - val_accuracy: 0.8429 - val_auc: 0.7869 - val_precision: 0.8611 - val_recall: 0.1462 - val_balanced_accuracy: 0.5750
Epoch 8/10
37/37 - 1s - loss: 0.4069 - accuracy: 0.8437 - auc: 0.7326 - precision: 0.7238 - recall: 0.2043 - balanced_accuracy: 0.5941 - val_loss: 0.3802 - val_accuracy: 0.8446 - val_auc: 0.7922 - val_precision: 0.8500 - val_recall: 0.1604 - val_balanced_accuracy: 0.5814
Epoch 9/10
37/37 - 0s - loss: 0.3990 - accuracy: 0.8458 - auc: 0.7459 - precision: 0.7241 - recall: 0.2231 - balanced_accuracy: 0.6018 - val_loss: 0.3759 - val_accuracy: 0.8488 - val_auc: 0.7960 - val_precision: 0.8667 - val_recall: 0.1840 - val_balanced_accuracy: 0.5917
Epoch 10/10
37/37 - 0s - loss: 0.3841 - accuracy: 0.8507 - auc: 0.7700 - precision: 0.7536 - recall: 0.2456 - balanced_accuracy: 0.6149 - val_loss: 0.3722 - val_accuracy: 0.8471 - val_auc: 0.7995 - val_precision: 0.8163 - val_recall: 0.1887 - val_balanced_accuracy: 0.5934
Epoch 00010: val_loss improved from inf to 0.37215, saving model to /home/zadubrov/output/results_train/AR_single-labeled_Fold-0.model.weights.hdf5
INFO     Computation time for training the single-label model for AR: 0.21 min
<IPython.core.display.HTML object>
[ True  True  True ...  True  True  True]
<bound method Model.predict of <keras.engine.sequential.Sequential object at 0x2adb5a2b7820>>
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
<class 'numpy.ndarray'>	4735
<class 'tuple'>	2
Traceback (most recent call last):
  File "/home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/__main__.py", line 415, in <module>
    main()
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/__main__.py", line 392, in main
    train(fixed_opts)
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/__main__.py", line 190, in train
    sl.train_single_label_models(df=df, opts=opts)
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/single_label_model.py", line 551, in train_single_label_models
    performance = fit_and_evaluate_model(x_train=x_train, x_test=x_test, y_train=y_train, y_test=y_test,
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/single_label_model.py", line 422, in fit_and_evaluate_model
    sd.shap_explain(x_train, x_test, model, target, opts.outputDir, drop_values=True, threshold=100, save_values=True)
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/shap_dfpl.py", line 27, in shap_explain
    explainer = shap.KernelExplainer(model, x_train[:x_train.shape():])
TypeError: 'tuple' object is not callable