WARNING:tensorflow:`period` argument is deprecated. Please use `save_freq` to specify the frequency in number of batches seen.
WARNING  `period` argument is deprecated. Please use `save_freq` to specify the frequency in number of batches seen.
Epoch 1/10
2023-04-03 15:30:23.478818: I tensorflow/core/grappler/devices.cc:66] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 4
2023-04-03 15:30:23.478989: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2023-04-03 15:30:23.509873: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 78600 MB memory:  -> device: 0, name: NVIDIA A100 80GB PCIe, pci bus id: 0000:17:00.0, compute capability: 8.0
2023-04-03 15:30:23.510863: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 78600 MB memory:  -> device: 1, name: NVIDIA A100 80GB PCIe, pci bus id: 0000:65:00.0, compute capability: 8.0
2023-04-03 15:30:23.511771: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:2 with 78600 MB memory:  -> device: 2, name: NVIDIA A100 80GB PCIe, pci bus id: 0000:ca:00.0, compute capability: 8.0
2023-04-03 15:30:23.512669: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:3 with 78600 MB memory:  -> device: 3, name: NVIDIA A100 80GB PCIe, pci bus id: 0000:e3:00.0, compute capability: 8.0
2023-04-03 15:30:23.527207: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:1137] Optimization results for grappler item: graph_to_optimize
  function_optimizer: function_optimizer did nothing. time = 0.025ms.
  function_optimizer: function_optimizer did nothing. time = 0.001ms.
WARNING:tensorflow:From /home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/site-packages/tensorflow/python/ops/math_ops.py:3777: tensor_shape_from_node_def_name (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.tensor_shape_from_node_def_name`
WARNING  From /home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/site-packages/tensorflow/python/ops/math_ops.py:3777: tensor_shape_from_node_def_name (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.tensor_shape_from_node_def_name`
2023-04-03 15:30:23.683820: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
2023-04-03 15:30:26.583139: I tensorflow/stream_executor/cuda/cuda_blas.cc:1760] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.
37/37 - 4s - loss: 0.5012 - accuracy: 0.8133 - auc: 0.5243 - precision: 0.2874 - recall: 0.0295 - balanced_accuracy: 0.5074 - val_loss: 0.4486 - val_accuracy: 0.8218 - val_auc: 0.6530 - val_precision: 0.6667 - val_recall: 0.0094 - val_balanced_accuracy: 0.5042
Epoch 2/10
37/37 - 0s - loss: 0.4692 - accuracy: 0.8180 - auc: 0.6057 - precision: 0.4312 - recall: 0.0555 - balanced_accuracy: 0.5189 - val_loss: 0.4288 - val_accuracy: 0.8345 - val_auc: 0.7019 - val_precision: 0.9444 - val_recall: 0.0802 - val_balanced_accuracy: 0.5508
Epoch 3/10
37/37 - 0s - loss: 0.4550 - accuracy: 0.8281 - auc: 0.6358 - precision: 0.5976 - recall: 0.1192 - balanced_accuracy: 0.5521 - val_loss: 0.4156 - val_accuracy: 0.8421 - val_auc: 0.7243 - val_precision: 0.9310 - val_recall: 0.1274 - val_balanced_accuracy: 0.5722
Epoch 4/10
37/37 - 0s - loss: 0.4404 - accuracy: 0.8296 - auc: 0.6690 - precision: 0.6099 - recall: 0.1311 - balanced_accuracy: 0.5560 - val_loss: 0.4062 - val_accuracy: 0.8446 - val_auc: 0.7396 - val_precision: 0.9375 - val_recall: 0.1415 - val_balanced_accuracy: 0.5783
Epoch 5/10
37/37 - 0s - loss: 0.4276 - accuracy: 0.8346 - auc: 0.6920 - precision: 0.6524 - recall: 0.1617 - balanced_accuracy: 0.5720 - val_loss: 0.3986 - val_accuracy: 0.8463 - val_auc: 0.7499 - val_precision: 0.9412 - val_recall: 0.1509 - val_balanced_accuracy: 0.5831
Epoch 6/10
37/37 - 0s - loss: 0.4198 - accuracy: 0.8359 - auc: 0.7108 - precision: 0.6636 - recall: 0.1677 - balanced_accuracy: 0.5744 - val_loss: 0.3923 - val_accuracy: 0.8480 - val_auc: 0.7597 - val_precision: 0.9211 - val_recall: 0.1651 - val_balanced_accuracy: 0.5888
Epoch 7/10
37/37 - 0s - loss: 0.4094 - accuracy: 0.8412 - auc: 0.7279 - precision: 0.7111 - recall: 0.1889 - balanced_accuracy: 0.5862 - val_loss: 0.3867 - val_accuracy: 0.8514 - val_auc: 0.7660 - val_precision: 0.8913 - val_recall: 0.1934 - val_balanced_accuracy: 0.6006
Epoch 8/10
37/37 - 0s - loss: 0.4053 - accuracy: 0.8456 - auc: 0.7350 - precision: 0.7302 - recall: 0.2172 - balanced_accuracy: 0.6001 - val_loss: 0.3819 - val_accuracy: 0.8514 - val_auc: 0.7725 - val_precision: 0.8913 - val_recall: 0.1934 - val_balanced_accuracy: 0.6006
Epoch 9/10
37/37 - 0s - loss: 0.3924 - accuracy: 0.8492 - auc: 0.7579 - precision: 0.7548 - recall: 0.2326 - balanced_accuracy: 0.6069 - val_loss: 0.3785 - val_accuracy: 0.8514 - val_auc: 0.7789 - val_precision: 0.8214 - val_recall: 0.2170 - val_balanced_accuracy: 0.6094
Epoch 10/10
37/37 - 0s - loss: 0.3867 - accuracy: 0.8492 - auc: 0.7666 - precision: 0.7367 - recall: 0.2444 - balanced_accuracy: 0.6140 - val_loss: 0.3744 - val_accuracy: 0.8514 - val_auc: 0.7840 - val_precision: 0.8103 - val_recall: 0.2217 - val_balanced_accuracy: 0.6108
Epoch 00010: val_loss improved from inf to 0.37440, saving model to /home/zadubrov/output/results_train/AR_single-labeled_Fold-0.model.weights.hdf5
INFO     Computation time for training the single-label model for AR: 0.13 min
<IPython.core.display.HTML object>
(array([0, 0, 0, ..., 0, 0, 0]), array([   0,    1,    2, ..., 2045, 2046, 2047]))
[False False False ... False False False]
Traceback (most recent call last):
  File "/home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/__main__.py", line 415, in <module>
    main()
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/__main__.py", line 392, in main
    train(fixed_opts)
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/__main__.py", line 190, in train
    sl.train_single_label_models(df=df, opts=opts)
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/single_label_model.py", line 551, in train_single_label_models
    performance = fit_and_evaluate_model(x_train=x_train, x_test=x_test, y_train=y_train, y_test=y_test,
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/single_label_model.py", line 422, in fit_and_evaluate_model
    sd.shap_explain(x_train, model, target, opts.outputDir, drop_values=True, threshold=10, save_values=True)
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/shap_dfpl.py", line 22, in shap_explain
    shap_values = explainer(x_train_to_explain)
  File "/home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/site-packages/shap/explainers/_permutation.py", line 68, in __call__
    return super().__call__(
  File "/home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/site-packages/shap/explainers/_permutation.py", line 82, in __call__
    return super().__call__(
  File "/home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/site-packages/shap/explainers/_explainer.py", line 266, in __call__
    row_result = self.explain_row(
  File "/home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/site-packages/shap/explainers/_permutation.py", line 92, in explain_row
    fm = MaskedModel(self.model, self.masker, self.link, self.linearize_link, *row_args)
  File "/home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/site-packages/shap/utils/_masked_model.py", line 45, in __init__
    self._masker_cols = mshape[1]
IndexError: tuple index out of range