WARNING:tensorflow:`period` argument is deprecated. Please use `save_freq` to specify the frequency in number of batches seen.
WARNING  `period` argument is deprecated. Please use `save_freq` to specify the frequency in number of batches seen.
Epoch 1/10
2023-04-04 10:20:46.272686: I tensorflow/core/grappler/devices.cc:66] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 4
2023-04-04 10:20:46.272975: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2023-04-04 10:20:46.309649: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 78600 MB memory:  -> device: 0, name: NVIDIA A100 80GB PCIe, pci bus id: 0000:17:00.0, compute capability: 8.0
2023-04-04 10:20:46.311290: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 78600 MB memory:  -> device: 1, name: NVIDIA A100 80GB PCIe, pci bus id: 0000:65:00.0, compute capability: 8.0
2023-04-04 10:20:46.313030: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:2 with 68 MB memory:  -> device: 2, name: NVIDIA A100 80GB PCIe, pci bus id: 0000:ca:00.0, compute capability: 8.0
2023-04-04 10:20:46.314672: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:3 with 78600 MB memory:  -> device: 3, name: NVIDIA A100 80GB PCIe, pci bus id: 0000:e3:00.0, compute capability: 8.0
2023-04-04 10:20:46.341428: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:1137] Optimization results for grappler item: graph_to_optimize
  function_optimizer: function_optimizer did nothing. time = 0.033ms.
  function_optimizer: function_optimizer did nothing. time = 0.001ms.
WARNING:tensorflow:From /home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/site-packages/tensorflow/python/ops/math_ops.py:3777: tensor_shape_from_node_def_name (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.tensor_shape_from_node_def_name`
WARNING  From /home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/site-packages/tensorflow/python/ops/math_ops.py:3777: tensor_shape_from_node_def_name (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.tensor_shape_from_node_def_name`
2023-04-04 10:20:46.627983: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
2023-04-04 10:20:52.386309: I tensorflow/stream_executor/cuda/cuda_blas.cc:1760] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.
37/37 - 7s - loss: 0.5028 - accuracy: 0.8103 - auc: 0.5324 - precision: 0.2617 - recall: 0.0331 - balanced_accuracy: 0.5058 - val_loss: 0.4540 - val_accuracy: 0.8218 - val_auc: 0.6082 - val_precision: 0.6667 - val_recall: 0.0094 - val_balanced_accuracy: 0.5043
Epoch 2/10
37/37 - 0s - loss: 0.4752 - accuracy: 0.8135 - auc: 0.5949 - precision: 0.3636 - recall: 0.0567 - balanced_accuracy: 0.5181 - val_loss: 0.4294 - val_accuracy: 0.8311 - val_auc: 0.6761 - val_precision: 0.8750 - val_recall: 0.0660 - val_balanced_accuracy: 0.5308
Epoch 3/10
37/37 - 0s - loss: 0.4525 - accuracy: 0.8249 - auc: 0.6429 - precision: 0.5600 - recall: 0.0992 - balanced_accuracy: 0.5404 - val_loss: 0.4130 - val_accuracy: 0.8421 - val_auc: 0.7115 - val_precision: 0.8788 - val_recall: 0.1368 - val_balanced_accuracy: 0.5625
Epoch 4/10
37/37 - 0s - loss: 0.4470 - accuracy: 0.8226 - auc: 0.6591 - precision: 0.5202 - recall: 0.1063 - balanced_accuracy: 0.5414 - val_loss: 0.4016 - val_accuracy: 0.8488 - val_auc: 0.7354 - val_precision: 0.8667 - val_recall: 0.1840 - val_balanced_accuracy: 0.5871
Epoch 5/10
37/37 - 0s - loss: 0.4293 - accuracy: 0.8355 - auc: 0.6899 - precision: 0.6735 - recall: 0.1558 - balanced_accuracy: 0.5702 - val_loss: 0.3929 - val_accuracy: 0.8530 - val_auc: 0.7506 - val_precision: 0.8800 - val_recall: 0.2075 - val_balanced_accuracy: 0.6002
Epoch 6/10
37/37 - 0s - loss: 0.4215 - accuracy: 0.8376 - auc: 0.7030 - precision: 0.6726 - recall: 0.1795 - balanced_accuracy: 0.5806 - val_loss: 0.3867 - val_accuracy: 0.8581 - val_auc: 0.7627 - val_precision: 0.8667 - val_recall: 0.2453 - val_balanced_accuracy: 0.6170
Epoch 7/10
37/37 - 0s - loss: 0.4104 - accuracy: 0.8422 - auc: 0.7289 - precision: 0.7000 - recall: 0.2066 - balanced_accuracy: 0.5917 - val_loss: 0.3810 - val_accuracy: 0.8573 - val_auc: 0.7726 - val_precision: 0.8525 - val_recall: 0.2453 - val_balanced_accuracy: 0.6166
Epoch 8/10
37/37 - 0s - loss: 0.4086 - accuracy: 0.8408 - auc: 0.7283 - precision: 0.6755 - recall: 0.2113 - balanced_accuracy: 0.5955 - val_loss: 0.3771 - val_accuracy: 0.8573 - val_auc: 0.7833 - val_precision: 0.8116 - val_recall: 0.2642 - val_balanced_accuracy: 0.6237
Epoch 9/10
37/37 - 0s - loss: 0.3949 - accuracy: 0.8450 - auc: 0.7555 - precision: 0.7070 - recall: 0.2279 - balanced_accuracy: 0.6037 - val_loss: 0.3727 - val_accuracy: 0.8581 - val_auc: 0.7876 - val_precision: 0.8143 - val_recall: 0.2689 - val_balanced_accuracy: 0.6259
Epoch 10/10
37/37 - 0s - loss: 0.3911 - accuracy: 0.8469 - auc: 0.7610 - precision: 0.7328 - recall: 0.2267 - balanced_accuracy: 0.6037 - val_loss: 0.3686 - val_accuracy: 0.8564 - val_auc: 0.7926 - val_precision: 0.7838 - val_recall: 0.2736 - val_balanced_accuracy: 0.6266
Epoch 00010: val_loss improved from inf to 0.36864, saving model to /home/zadubrov/output/results_train/AR_single-labeled_Fold-0.model.weights.hdf5
<IPython.core.display.HTML object>
<class 'tuple'>	2	(1885,)
<class 'numpy.ndarray'>	1885
INFO     Computation time for training the single-label model for AR: 0.2 min
Traceback (most recent call last):
  File "/home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/__main__.py", line 415, in <module>
    main()
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/__main__.py", line 392, in main
    train(fixed_opts)
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/__main__.py", line 190, in train
    sl.train_single_label_models(df=df, opts=opts)
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/single_label_model.py", line 551, in train_single_label_models
    performance = fit_and_evaluate_model(x_train=x_train, x_test=x_test, y_train=y_train, y_test=y_test,
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/single_label_model.py", line 422, in fit_and_evaluate_model
    sd.shap_explain(x_train, model, target, opts.outputDir, drop_values=True, threshold=10, save_values=True)
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/shap_dfpl.py", line 22, in shap_explain
    shap_values = explainer(x_train_to_explain)
  File "/home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/site-packages/shap/explainers/_permutation.py", line 68, in __call__
    return super().__call__(
  File "/home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/site-packages/shap/explainers/_permutation.py", line 82, in __call__
    return super().__call__(
  File "/home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/site-packages/shap/explainers/_explainer.py", line 266, in __call__
    row_result = self.explain_row(
  File "/home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/site-packages/shap/explainers/_permutation.py", line 92, in explain_row
    fm = MaskedModel(self.model, self.masker, self.link, self.linearize_link, *row_args)
  File "/home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/site-packages/shap/utils/_masked_model.py", line 45, in __init__
    self._masker_cols = mshape[1]
IndexError: tuple index out of range